[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "eras"
url = "app/static/eras-medium.ttf"
style = "normal"
weight = 500

[[theme.fontFaces]]
family = "eras"
url = "app/static/eras-demi.ttf"
style = "normal"
weight = 800

[[theme.fontFaces]]
family = "eras"
url = "app/static/eras-bold.ttf"
style = "normal"
weight = 900

[theme]
primaryColor = "#e00a1d"
backgroundColor = "#f4f6fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
font = "eras"
headingFont = "eras"
baseFontWeight = 500
baseRadius = "0.85rem"
buttonRadius = "full"
